export const ADD_NEW_NODE_LIST = 'NODE_LIST/THEME_REDUCER/ADD_NEW_NODE_LIST';
export const REMOVE_NODE_LIST = 'NODE_LIST/THEME_REDUCER/REMOVE_NODE_LIST';
export const ADD_NEW_NODE_IN_LIST = 'NODE_LIST/THEME_REDUCER/ADD_NEW_NODE_IN_LIST';
