export const ADD_NEW_NODE_LIST = 'NODE_LIST/THEME_REDUCER/ADD_NEW_NODE_LIST';
export const REMOVE_NODE_LIST = 'NODE_LIST/THEME_REDUCER/REMOVE_NODE_LIST';
export const ADD_NEW_NODE_IN_LIST = 'NODE_LIST/THEME_REDUCER/ADD_NEW_NODE_IN_LIST';
export const REMOVE_NODE_FROM_LIST = 'NODE_LIST/THEME_REDUCER/REMOVE_NODE_FROM_LIST';
export const CHANGE_NODE_STATUS_IN_LIST =
  'NODE_LIST/THEME_REDUCER/CHANGE_NODE_STATUS_IN_LIST';
export const SET_CURRENT_LIST_IN_LOCAL_STORAGE =
  'NODE_LIST/THEME_REDUCER/SET_CURRENT_LIST_IN_LOCAL_STORAGE';
